# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        our_db_provider:
             entity:
                 class: AppBundle:User


    encoders:
        AppBundle\Entity\User:
              algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
            logout:
                path:   /logout
                target: /
            remember_me:
                            secret:   '%secret%'
                            lifetime: 604800 # 1 week in seconds
                            path:     /

    access_control:
         # require ROLE_ADMIN for /admin*
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/userpage, roles: ROLE_USER }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/(en|ru)/categories$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/products$, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_USER] }
         - { path: ^/(en|ru)/product_page$, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_USER] }
         - { path: ^/(en|ru)/product_view$, roles: [ROLE_ADMIN, ROLE_EDITOR, ROLE_USER] }
         - { path: ^/(en|ru)/category_create$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/category_edit$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/category_delete$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/category_create$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/product$, roles: [ROLE_ADMIN, ROLE_EDITOR] }
         - { path: ^/(en|ru)/user$, roles: [ROLE_ADMIN] }
         - { path: ^/(en|ru)/user_list$, roles: [ROLE_ADMIN] }


