# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        our_db_provider:
             entity:
                 class: AppBundle:User
                 property: username

    encoders:
        AppBundle\Entity\User:
              algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
    access_control:
         # require ROLE_ADMIN for /admin*
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/user*, roles: ROLE_USER }
#Надо сделать иерархию ролей(их 3 штуки + анонимные пользователи). Создать онтроллеры для всех будущих ресурсов. Могут возвращать заглушки.
#